name: ML CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  preprocess:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get AWS Identity Info
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws sts get-caller-identity
