name: ML CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  preprocess:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Preprocess steps
        run: python scripts/feed_back_model/pre-process.py
